[package]
name = "juicebox_process_group"
version.workspace = true
license.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
libc = { workspace = true }
nix = { workspace = true }
tracing = { workspace = true }
