[workspace]
members = [
    "rust/sdk/client",
    "rust/sdk/core",
    "rust/sdk/networking",
    "rust/bridge/ffi",
]
default-members = [
    "rust/sdk/client",
]

[workspace.dependencies]
async-trait = "0.1.64"
ciborium = { version = "0.2.0", default-features = false }
digest = { version = "0.10.6" }
futures = { version = "0.3.25" }
hmac = "0.12.1"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
serde = { version = "1.0.152", default-features = false, features = [
    "alloc",
    "derive",
] }
sha2 = { version = "0.10.6", default-features = false }
sharks = "0.5.0"
subtle = { version = "2.4.1", default-features = false }
tracing = { git = "https://github.com/tokio-rs/tracing", version = "0.2.0", default-features = false, features = [
    "alloc",
    "attributes",
] }
# The latest Cargo.toml of tracing-opentelemetry in Git has an old version number.
tracing-opentelemetry = { git = "https://github.com/tokio-rs/tracing", version = "*" }
url = "2.3.1"
voprf = { version = "0.4.0" }
