[workspace]
members = [
    "rust/sdk/client",
    "rust/sdk/core",
    "rust/sdk/networking",
    "rust/sdk/noise",
    "rust/bridge/ffi",
    "rust/bridge/jni",
    "rust/bridge/wasm",
    "rust/bridge/common",
]
default-members = ["rust/sdk/client"]

[workspace.dependencies]
async-trait = "0.1.64"
blake2 = { version = "0.10.6", default-features = false }
console_error_panic_hook = "0.1.6"
chacha20poly1305 = { version = "0.10.1", default-features = false, features = [
    "alloc",
] }
cbindgen = "0.24.3"
ciborium = { version = "0.2.0", default-features = false }
digest = { version = "0.10.6" }
futures = { version = "0.3.25" }
getrandom = "0.2.8"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
hkdf = "0.12.3"
hmac = "0.12.1"
http = "0.2.8"
instant = "0.1.12"
jni = "0.21.1"
js-sys = "0.3.61"
libc = "0.2.140"
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_core = "0.6.4"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.152", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = "1.0.94"
serde-wasm-bindgen = "0.5"
sha2 = { version = "0.10.6", default-features = false }
sharks = "0.5.0"
subtle = { version = "2.4.1", default-features = false }
tokio = { version = "1.25.0", features = ["sync"] }
tracing = { git = "https://github.com/tokio-rs/tracing", version = "0.2.0", default-features = false, features = [
    "alloc",
    "attributes",
] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.0", features = ["v4"] }
voprf = { version = "0.4.0" }
wasm-bindgen = { version = "0.2.84", features = ["serde"] }
wasm-bindgen-futures = "0.4.34"
wasm-bindgen-test = "0.3.34"
web-sys = { version = "0.3.4", features = ["Headers", "Request", "RequestInit", "RequestMode", "Response", "Window", "Blob"] }
x25519-dalek = { version = "2.0.0-pre.1", default-features = false, features = [
    "reusable_secrets",
    "serde",
    "u64_backend",      # TODO: need 32-bit on HSMs
] }

[patch.crates-io]
secrecy = { git = "ssh://git@github.com/Loam-Security/secrecy.git", branch = "loam-main" }
