[package]
name = "juicebox-sdk-process-group"
version.workspace = true
license.workspace = true
edition = "2021"

[dependencies]
libc = { workspace = true }
nix = { workspace = true }
tracing = { workspace = true }
