[package]
name = "loam-sdk"
version = "0.1.0"
authors = [
    "Simon Fell <simon@loam.me>",
    "Diego Ongaro <diego@loam.me>",
    "Nora Trapp <nora@loam.me>",
]
edition = "2021"

[lib]
doctest = false

[dependencies]
argon2 = { workspace = true }
async-trait = { workspace = true }
blake2 = { workspace = true }
chacha20poly1305 = { workspace = true }
digest = { workspace = true }
futures = { workspace = true }
hmac = { workspace = true }
instant = { workspace = true }
loam-sdk-core = { path = "../../sdk/core" }
loam-sdk-networking = { path = "../../sdk/networking" }
loam-sdk-noise = { path = "../../sdk/noise" }
rand = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
sharks = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
voprf = { workspace = true }
x25519-dalek = { workspace = true }

[features]
tokio = []
