[package]
name = "loam-sdk-networking"
version = "0.1.0"
authors = [
    "Simon Fell <simon@loam.me>",
    "Diego Ongaro <diego@loam.me>",
    "Nora Trapp <nora@loam.me>",
]
edition = "2021"

[dependencies]
async-trait = { workspace = true }
http = { workspace = true }
loam-sdk-core = { path = "../../sdk/core" }
opentelemetry = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
url = { workspace = true }
