[package]
name = "loam-sdk-core"
version = "0.1.0"
authors = ["Simon Fell <simon@loam.me", "Diego Ongaro <diego@loam.me>", "Nora Trapp <nora@loam.me>"]
edition = "2021"

[dependencies]
ciborium = { version = "0.2.0", default-features = false }
digest = { version = "0.10.6" }
serde = { version = "1.0.152", default-features = false, features = [
    "alloc",
    "derive",
] }
subtle = { version = "2.4.1", default-features = false }
voprf = { version = "0.4.0" }
