[package]
name = "loam-sdk-core"
version = "0.1.0"
authors = [
    "Simon Fell <simon@loam.me",
    "Diego Ongaro <diego@loam.me>",
    "Nora Trapp <nora@loam.me>",
]
edition = "2021"

[dependencies]
ciborium = { workspace = true }
digest = { workspace = true }
loam-sdk-noise = { path = "../../sdk/noise" }
serde = { workspace = true }
subtle = { workspace = true }
voprf = { workspace = true }
