[package]
name = "juicebox_sdk_jni"
version.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
jni = { workspace = true }
juicebox_sdk = { workspace = true }
juicebox_sdk_bridge = { workspace = true, features = ["tokio"] }
rand_core = { workspace = true }
url = { workspace = true }
