# This is based on
# <https://github.com/ongardie/cubicle/blob/b307fe9/.github/workflows/main.yaml>
# with Diego's permission.  The initial workflow YAML skeleton before that was
# based on
# <https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml>
# and
# <https://github.com/ramosbugs/oauth2-rs/blob/main/.github/workflows/main.yml>.
#
# GitHub Actions workflow syntax documentation is here:
# <https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions>.
name: Manual CI

on:
  workflow_dispatch: {}

jobs:
  android:
    name: Android
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: |
        rustup toolchain install 1.71 --profile minimal --target aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
        rustup default 1.71

    - name: Use Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'gradle'

    - name: Build and Test
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: google_apis
        arch: x86_64
        working-directory: ./android
        script: ./gradlew connectedCheck
