name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  INSTALL_RUST_VERSION: "1.73"
  
jobs:
  whitepaper:
    name: Whitepaper
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Compile Whitepaper
        uses: lvignoli/typst-action@main
        with:
          source_file: whitepaper/whitepaper.typ

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_DOCUMENTATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync Whitepaper to Google Cloud Storage
        run: |
          WHITEPAPER_DATE=$(date -d "$(awk -F'["]' '/date:/ { print $2 }' whitepaper.typ)" +"%Y%m%d")
          WHITEPAPER_REVISION=$(awk -F'["]' '/version:/ { gsub(/ /, "", $2); print tolower($2) }' whitepaper.typ)
          WHITEPAPER_NAME=juiceboxprotocol_${WHITEPAPER_REVISION}_${WHITEPAPER_DATE}.pdf
          gsutil -m cp whitepaper.pdf \
          gs://e2d3e242bbd420b1f977a1f84684a45f1803a5b4/whitepapers/${WHITEPAPER_NAME}
        working-directory: whitepaper

  swift:
    name: Swift
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Documentation
        run: |
          swift package --allow-writing-to-directory docs \
          generate-documentation --target JuiceboxSdk --disable-indexing \
          --output-path docs \
          --transform-for-static-hosting \
          --hosting-base-path swift
        working-directory: swift

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_DOCUMENTATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync Docs to Google Cloud Storage
        run: |
          gsutil -m rsync -r \
          -d swift/docs \
          gs://e2d3e242bbd420b1f977a1f84684a45f1803a5b4/swift

  rust:
    name: Rust
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          toolchain: ${{ env.INSTALL_RUST_VERSION }}

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Generate Documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: '-p juicebox_sdk --no-deps --features tokio,reqwest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_DOCUMENTATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync Docs to Google Cloud Storage
        run: |
          gsutil -m rsync -r \
          -d target/doc \
          gs://e2d3e242bbd420b1f977a1f84684a45f1803a5b4/rust

  android:
    name: Android
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup toolchain install ${{ env.INSTALL_RUST_VERSION }} --profile minimal --target \
            aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
          rustup default ${{ env.INSTALL_RUST_VERSION }}

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          cache: gradle

      - name: Generate Documentation
        run: ./gradlew dokkaHtml
        working-directory: android

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_DOCUMENTATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync Docs to Google Cloud Storage
        run: |
          gsutil -m rsync -r \
          -d android/build/dokka/html \
          gs://e2d3e242bbd420b1f977a1f84684a45f1803a5b4/android

  js:
    name: JavaScript
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          toolchain: ${{ env.INSTALL_RUST_VERSION }}

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Create JavaScript package
        run: wasm-pack build rust/sdk/bridge/wasm --out-dir ../../../../javascript/juicebox-sdk --out-name juicebox-sdk --target nodejs

      - name: Install TypeDoc
        run: npm install --global typedoc

      - name: Generate Documentation
        run: typedoc
        working-directory: javascript/juicebox-sdk

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_DOCUMENTATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync Docs to Google Cloud Storage
        run: |
          gsutil -m rsync -r \
          -d javascript/juicebox-sdk/docs \
          gs://e2d3e242bbd420b1f977a1f84684a45f1803a5b4/javascript
