name: Publishing

on:
  push:
    tags:
      - '*'

jobs:
  android:
    name: Android
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: >-
          rustup toolchain install stable --profile minimal --target
          aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          cache: gradle

      - name: Publish
        run: >-
          gradlew clean publish
          -PossrhUsername="${{ secrets.OSSRH_USERNAME }}"
          -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}"
          -PsigningPassword="${{ secrets.ANDROID_SIGNING_PASSWORD }}"
          -PsigningKey="${{ secrets.ANDROID_SIGNING_KEY }}"
        working-directory: android
