name: Publishing

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-?**'

env:
  INSTALL_RUST_VERSION: "1.74"

jobs:
  android:
    name: Android
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build juicebox_sdk_jni
        run: |
          ./artifacts/build.sh --verbose --jni

      - name: Check Artifacts Status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Artifact changes have not been committed, make and commit your changes before tagging."
            git diff
            exit 1
          fi
        working-directory: artifacts

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          cache: gradle

      - name: Publish
        run: >-
          ./gradlew clean publish
          -PossrhUsername="${{ secrets.OSSRH_USERNAME }}"
          -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}"
          -PsigningPassword="${{ secrets.ANDROID_SIGNING_PASSWORD }}"
          -PsigningKey="${{ secrets.ANDROID_SIGNING_KEY }}"
        working-directory: android

  javascript:
    name: JavaScript
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          toolchain: ${{ env.INSTALL_RUST_VERSION }}

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Build JavaScript Package
        run: >-
          wasm-pack build rust/sdk/bridge/wasm
          --out-dir ../../../../javascript/juicebox-sdk
          --out-name juicebox-sdk
          --target bundler

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        run: |
          cp ../README.md .
          sed -i 's/juicebox_sdk_wasm/juicebox-sdk/' package.json
          npm publish
        working-directory: javascript/juicebox-sdk
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"

  cocoapods:
    name: CocoaPods
    runs-on: macOS-12-large
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build juicebox_sdk_ffi
        run: |
          brew install docker
          colima start
          ./artifacts/build.sh --verbose --ffi

      - name: Check Artifacts Status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Artifact changes have not been committed, make and commit your changes before tagging."
            git diff
            exit 1
          fi
        working-directory: artifacts

      - name: Publish
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.ACCESS_KEY }}"
          pod trunk push --verbose --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: "${{ secrets.COCOAPODS_TRUNK_TOKEN }}"
